---
openapi: 3.1.0
paths:
  /api/admin/stats:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int64
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Stats
      tags:
        - Admin Resource
      security:
        - SecurityScheme:
            - admin
  /api/admin/users:
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
        - name: query
          in: query
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: integer
            format: int32
            default: 10
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/UserStatus"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPageResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: List Users
      tags:
        - Admin Resource
      security:
        - SecurityScheme:
            - admin
  /api/admin/users/{userId}/status:
    put:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StatusUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Update Status
      tags:
        - Admin Resource
      security:
        - SecurityScheme:
            - admin
  /api/users/me:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
      summary: Me
      tags:
        - User Resource
  /api/users/profile:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "400":
          description: Bad Request
      summary: Update Profile
      tags:
        - User Resource
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Hello
      tags:
        - Greeting Resource
  /q/health:
    description: MicroProfile Health Endpoint
    summary:
      MicroProfile Health provides a way for your application to distribute
      information about its healthiness state to state whether or not it is able to
      function properly
    get:
      operationId: microprofile_health_root
      description: Check the health of the application
      tags:
        - MicroProfile Health
      summary:
        "An aggregated view of the Liveness, Readiness and Startup of this\
        \ application"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /q/health/live:
    description: MicroProfile Health - Liveness Endpoint
    summary:
      Liveness checks are utilized to tell whether the application should be
      restarted
    get:
      operationId: microprofile_health_liveness
      description: Check the liveness of the application
      tags:
        - MicroProfile Health
      summary: The Liveness check of this application
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /q/health/ready:
    description: MicroProfile Health - Readiness Endpoint
    summary:
      Readiness checks are used to tell whether the application is able to
      process requests
    get:
      operationId: microprofile_health_readiness
      description: Check the readiness of the application
      tags:
        - MicroProfile Health
      summary: The Readiness check of this application
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /q/health/started:
    description: MicroProfile Health - Startup Endpoint
    summary: Startup checks are an used to tell when the application has started
    get:
      operationId: microprofile_health_startup
      description: Check the startup of the application
      tags:
        - MicroProfile Health
      summary: The Startup check of this application
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
components:
  schemas:
    Instant:
      type: string
      format: date-time
      examples:
        - 2022-03-10T16:15:50Z
    StatusUpdateRequest:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/UserStatus"
    UpdateProfileRequest:
      type: object
      required:
        - displayName
      properties:
        displayName:
          type: string
          maxLength: 50
          pattern: \S
    UserPageResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        data:
          type: array
          items:
            $ref: "#/components/schemas/UserProfile"
        page:
          type: integer
          format: int32
    UserProfile:
      type: object
      properties:
        userId:
          type: string
        email:
          type: string
        displayName:
          type: string
        status:
          $ref: "#/components/schemas/UserStatus"
        isEmailSynced:
          type: boolean
        createdAt:
          $ref: "#/components/schemas/Instant"
        updatedAt:
          $ref: "#/components/schemas/Instant"
    UserStatus:
      type: string
      enum:
        - ACTIVE
        - PENDING
        - DELETED
        - SUSPENDED
    HealthResponse:
      type: object
      properties:
        checks:
          type: array
          items:
            $ref: "#/components/schemas/HealthCheck"
        status:
          type: string
          enum:
            - UP
            - DOWN
    HealthCheck:
      type: object
      properties:
        data:
          type:
            - object
            - "null"
        name:
          type: string
        status:
          type: string
          enum:
            - UP
            - DOWN
  securitySchemes:
    SecurityScheme:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: http://localhost:8180/realms/cyrene/.well-known/openid-configuration
tags:
  - name: MicroProfile Health
    description: Check the health of the application
info:
  title: cyrene API
  version: 0.1.0
